# Generated by Django 2.1.4 on 2018-12-18 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('seq_id', models.PositiveIntegerField(default=1)),
                ('is_system', models.BooleanField(default=0, help_text='System required fields')),
                ('is_active', models.BooleanField(default=1, help_text='Allows a record to be toggled inactive')),
                ('number', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=255)),
                ('created_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='default_api_order_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='default_api_order_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
